### PR TITLE
AA-2835 add webinars section to resource

### PR DESCRIPTION
**Pull request by ShiraziElham**
What needs to be tested? A new section in "Resource" page is created. please see if it meets user requests.

### CODE REVIEW

**Comment by wesleymartin-ab** [comment]
Eli it looks great! Umm dont merge it yet, we need to figure out proper testing, and I want to make sure we dont mess with the release plan for the SDCC ticket, but I think you can consider this done. Maybe branch off of this branch to start the next ticket?

**Comment by ShiraziElham** [comment]
> Eli it looks great! Umm dont merge it yet, we need to figure out proper testing, and I want to make sure we dont mess with the release plan for the SDCC ticket, but I think you can consider this done. Maybe branch off of this branch to start the next ticket?

I am going to add the next ticket in the same branch and keep jira ticket number in following commits and also link these 2 jira tickets together. Are you OK with it?

**Comment by wesleymartin-ab** [comment]
For sure, sounds good

**Comment by ShiraziElham** [comment]
> For sure, sounds good



> For sure, sounds good

Just did so. Please review it.

**Comment by wesleymartin-ab** [comment]
Looks great Eli!! Still need Jude to review it, but I think its all set!

**Comment by ShiraziElham** [comment]
New process change:
    Master is going to be reserved to keep sync with prod. And dev is going to be base for all new tickets.
This changes are merged into dev. And this PR is going to be closed manually.

**Pull request closed without merging**
